CREATE TABLE input_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   billing_header_id BIGINT,
   CONSTRAINT pk_inputrequest PRIMARY KEY (id)
);

CREATE TABLE billing_header (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   billing_id VARCHAR(255),
   invoice_date VARCHAR(255),
   total_invoice_amount DOUBLE PRECISION,
   CONSTRAINT pk_billingheader PRIMARY KEY (id)
);

ALTER TABLE input_request ADD CONSTRAINT FK_INPUTREQUEST_ON_BILLING_HEADER FOREIGN KEY (billing_header_id) REFERENCES billing_header (id);

CREATE TABLE billing_line_information (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   input_request_id BIGINT,
   product_type VARCHAR(255),
   line_type VARCHAR(255),
   CONSTRAINT pk_billinglineinformation PRIMARY KEY (id)
);

ALTER TABLE billing_line_information ADD CONSTRAINT FK_BILLINGLINEINFORMATION_ON_INPUT_REQUEST FOREIGN KEY (input_request_id) REFERENCES input_request (id);

-- Insert data into BillingHeader
INSERT INTO billing_header (billing_id, invoice_date, total_invoice_amount)
VALUES ('BILL001', '2024-11-01', 1500.00);

-- Insert data into InputRequest
INSERT INTO input_request (billing_header_id)
VALUES (1);

-- Insert data into BillingLineInformation
INSERT INTO billing_line_information (input_request_id, product_type, line_type)
VALUES
    (1, 'ProductA', 'Type1'),
    (1, 'ProductB', 'Type2');